name: openssl_ecdsa
description: OpenSSL ECDSA Bindings for Dart

environment:
  sdk: ^3.8.0
dependencies:
  crypto: ^3.0.6
  ffi: ^2.1.4
  file: ^7.0.1
  glob: ^2.1.3
dev_dependencies:
  ffigen: ^19.1.0
  test: ^1.26.3
