version: 2
updates:
  - package-ecosystem: "pub"
    directory: '/'
    schedule:
      interval: "monthly"
    commit_message:
      prefix: "[dependabot]"
  - package-ecosystem: "npm"
    directory: "web"
    schedule:
      interval: "monthly"
    commit_message:
      prefix: "[dependabot]"
