version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    reviewers:
      - nikeokoronkwo
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[deps] "
  - package-ecosystem: "npm"
    directory: "web"
    reviewers:
      - nikeokoronkwo
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[deps] "
