version: 2
updates:
  - package-ecosystem: "pub"
    directories: ["common", "cli", "server"]
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "web"
    schedule:
      interval: "monthly"