# Created with package:mono_repo v6.6.3
{
  "version": 2,
  "updates": [
    {
      "package-ecosystem": "pub",
      "directories": [
        "common",
        "packages/*",
        "cli",
        "server"
      ],
      "schedule": {
        "interval": "monthly"
      }
    },
    {
      "package-ecosystem": "npm",
      "directory": "web",
      "schedule": {
        "interval": "monthly"
      }
    }
  ]
}
