include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_relative_imports
    - sort_pub_dependencies

formatter:
  page_width: 80