include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - annotate_redeclares
    - avoid_bool_literals_in_conditional_expressions
    - avoid_returning_this
    - avoid_private_typedef_functions
    - directives_ordering
    - flutter_style_todos
    - join_return_with_assignment
    - no_runtimeType_toString
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_relative_imports
    - slash_for_doc_comments
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_parenthesis
    - unreachable_from_main
    - type_annotate_public_apis
    - use_named_constants
    - use_string_buffers

analyzer:
  exclude:
    - e2e/**
  errors:
    todo: ignore

formatter:
  page_width: 80
