name: pritt

services:
  
  filestorage:
    image: openio/sds
    ports:
      - "6007:6007"
    environment:
      REGION: ${S3_REGION}
      SWIFT_CREDENTIALS: "${S3_SECRET_KEY}:${S3_ACCESS_KEY}:.admin"
      WORKERS: ${S3_WORKERS}
    env_file:
      - .env
    volumes:
      - adapter-fs-data:/var/lib/oio/sds/OPENIO/rawx-0

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env

volumes:
  adapter-fs-data:
    name: "adapter_fs_data"