name: pritt

services:
  server:
    build:
      context: .
      dockerfile: server/workspace.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env

  
    