name: pritt_cli
description: The command-line interface to Pritt
version: 0.1.0-wip
# repository: https://github.com/my_org/my_repo
resolution: workspace

executables:
  pritt:

environment:
  sdk: ^3.8.0


dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  chunked_stream: ^1.4.2
  crypto: ^3.0.6
  glob: ^2.1.3
  http: ^1.4.0
  io: ^1.0.5
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  pritt_common: ^0.1.0-wip
  retry: ^3.1.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  cli_pkg: ^2.12.0
  grinder: ^0.9.5
  json_serializable: ^6.9.5
  lints: ^6.0.0
  mockito: ^5.4.5
  test: ^1.25.15
