name: pritt_cli
description: The command-line interface to Pritt
version: 0.0.1
# repository: https://github.com/my_org/my_repo
resolution: workspace

executables:
  pritt:

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  glob: ^2.1.3
  http: ^1.4.0
  io: ^1.0.5
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  pritt_common: ^0.0.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  cli_pkg: ^2.12.0
  grinder: ^0.9.5
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.25.15
