name: pritt_adapter
version: 0.1.0-wip
resolution: workspace

environment:
  sdk: ^3.8.0
dependencies:
  archive: ^3.6.1
  chunked_stream: ^1.4.2
  html: ^0.15.6
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_rpc_2: ^4.0.0
  mime: ^2.0.0
  path: ^1.9.1
  pritt_common: ^0.1.0-wip
  pritt_server_core: ^0.1.0-wip
  web_socket_channel: ^3.0.3
  yaml: ^3.1.3
dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  mockito: ^5.5.0
  test: ^1.26.3
