name: pritt_server

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^3.6.1
  async: ^2.13.0
  aws_s3_api: ^2.0.0
  aws_signer_api: ^2.0.0
  chunked_stream: ^1.4.2
  crypto: ^3.0.6
  file: ^7.0.1
  html: ^0.15.6
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_rpc_2: ^4.0.0
  logging: ^1.3.0
  mime: ^2.0.0
  path: ^1.9.1
  pool: ^1.5.1
  postgres: ^3.5.6
  pritt_common: ^0.0.1
  retry: ^3.1.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  slugid: ^1.1.2
  sqlite3: ^2.7.6
  web_socket_channel: ^3.0.3
  xml: ^6.4.0
  yaml: ^3.1.3

dev_dependencies:
  args: ^2.7.0
  benchmark_harness: ^2.3.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mockito: ^5.4.5
  test: ^1.25.15
