name: pritt_server

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  aws_s3_api: ^2.0.0
  json_annotation: ^4.9.0
  mime: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  yaml: ^3.1.3
dev_dependencies:
  test: ^1.25.15
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

