// Mocks generated by Mockito 5.4.6 from annotations
// in pritt_server/test/unit/adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pritt_server/src/main/base/db/interface.dart' as _i2;
import 'package:pritt_server/src/main/base/db/schema.dart' as _i7;
import 'package:pritt_server/src/main/base/storage/interface.dart' as _i3;
import 'package:pritt_server/src/main/crs/interfaces.dart' as _i4;
import 'package:pritt_server/src/main/crs/response.dart' as _i6;
import 'package:pritt_server/src/main/utils/mixins.dart' as _i10;
import 'package:pritt_server/src/main/utils/version.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePrittDatabaseInterface_0 extends _i1.SmartFake
    implements _i2.PrittDatabaseInterface {
  _FakePrittDatabaseInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrittStorageInterface_1 extends _i1.SmartFake
    implements _i3.PrittStorageInterface {
  _FakePrittStorageInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CRSDBController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCRSDBController extends _i1.Mock implements _i4.CRSDBController {
  MockCRSDBController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrittDatabaseInterface get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakePrittDatabaseInterface_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.PrittDatabaseInterface);

  @override
  _i5.Future<_i6.CRSResponse<_i7.PackageVersions>> getLatestPackage(
    String? packageName, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestPackage,
          [packageName],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue: _i5.Future<_i6.CRSResponse<_i7.PackageVersions>>.value(
            _i8.dummyValue<_i6.CRSResponse<_i7.PackageVersions>>(
          this,
          Invocation.method(
            #getLatestPackage,
            [packageName],
            {
              #language: language,
              #env: env,
            },
          ),
        )),
      ) as _i5.Future<_i6.CRSResponse<_i7.PackageVersions>>);

  @override
  _i5.Future<_i6.CRSResponse<_i7.PackageVersions>> getPackageWithVersion(
    String? packageName,
    String? version, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackageWithVersion,
          [
            packageName,
            version,
          ],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue: _i5.Future<_i6.CRSResponse<_i7.PackageVersions>>.value(
            _i8.dummyValue<_i6.CRSResponse<_i7.PackageVersions>>(
          this,
          Invocation.method(
            #getPackageWithVersion,
            [
              packageName,
              version,
            ],
            {
              #language: language,
              #env: env,
            },
          ),
        )),
      ) as _i5.Future<_i6.CRSResponse<_i7.PackageVersions>>);

  @override
  _i5.Future<
      _i6.CRSResponse<Map<_i9.Version, _i7.PackageVersions>>> getPackages(
    String? packageName, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackages,
          [packageName],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue: _i5.Future<
                _i6.CRSResponse<Map<_i9.Version, _i7.PackageVersions>>>.value(
            _i8.dummyValue<
                _i6.CRSResponse<Map<_i9.Version, _i7.PackageVersions>>>(
          this,
          Invocation.method(
            #getPackages,
            [packageName],
            {
              #language: language,
              #env: env,
            },
          ),
        )),
      ) as _i5.Future<_i6.CRSResponse<Map<_i9.Version, _i7.PackageVersions>>>);

  @override
  _i6.CRSResponse<_i5.Stream<_i7.PackageVersions>> getPackagesStream(
    String? packageName, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackagesStream,
          [packageName],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue:
            _i8.dummyValue<_i6.CRSResponse<_i5.Stream<_i7.PackageVersions>>>(
          this,
          Invocation.method(
            #getPackagesStream,
            [packageName],
            {
              #language: language,
              #env: env,
            },
          ),
        ),
      ) as _i6.CRSResponse<_i5.Stream<_i7.PackageVersions>>);

  @override
  _i5.Future<_i6.CRSResponse<_i7.Package>> getPackageDetails(
    String? packageName, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackageDetails,
          [packageName],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue: _i5.Future<_i6.CRSResponse<_i7.Package>>.value(
            _i8.dummyValue<_i6.CRSResponse<_i7.Package>>(
          this,
          Invocation.method(
            #getPackageDetails,
            [packageName],
            {
              #language: language,
              #env: env,
            },
          ),
        )),
      ) as _i5.Future<_i6.CRSResponse<_i7.Package>>);

  @override
  _i5.Future<_i6.CRSResponse<Map<_i7.User, Iterable<_i7.Privileges>>>>
      getPackageContributors(
    String? packageName, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getPackageContributors,
              [packageName],
              {
                #language: language,
                #env: env,
              },
            ),
            returnValue: _i5.Future<
                    _i6.CRSResponse<
                        Map<_i7.User, Iterable<_i7.Privileges>>>>.value(
                _i8.dummyValue<
                    _i6.CRSResponse<Map<_i7.User, Iterable<_i7.Privileges>>>>(
              this,
              Invocation.method(
                #getPackageContributors,
                [packageName],
                {
                  #language: language,
                  #env: env,
                },
              ),
            )),
          ) as _i5.Future<
              _i6.CRSResponse<Map<_i7.User, Iterable<_i7.Privileges>>>>);
}

/// A class which mocks [CRSArchiveController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCRSArchiveController extends _i1.Mock
    implements _i4.CRSArchiveController {
  MockCRSArchiveController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PrittStorageInterface get ofs => (super.noSuchMethod(
        Invocation.getter(#ofs),
        returnValue: _FakePrittStorageInterface_1(
          this,
          Invocation.getter(#ofs),
        ),
      ) as _i3.PrittStorageInterface);

  @override
  _i5.Future<_i6.CRSResponse<_i4.CRSArchive>> getArchiveWithVersion(
    String? packageName,
    String? version, {
    String? language,
    Map<String, dynamic>? env,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchiveWithVersion,
          [
            packageName,
            version,
          ],
          {
            #language: language,
            #env: env,
          },
        ),
        returnValue: _i5.Future<_i6.CRSResponse<_i4.CRSArchive>>.value(
            _i8.dummyValue<_i6.CRSResponse<_i4.CRSArchive>>(
          this,
          Invocation.method(
            #getArchiveWithVersion,
            [
              packageName,
              version,
            ],
            {
              #language: language,
              #env: env,
            },
          ),
        )),
      ) as _i5.Future<_i6.CRSResponse<_i4.CRSArchive>>);

  @override
  _i5.FutureOr<dynamic> setFileServer(
    String? packageName, {
    String? version,
    String? language,
    bool? cache = false,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #setFileServer,
        [packageName],
        {
          #version: version,
          #language: language,
          #cache: cache,
        },
      )) as _i5.FutureOr<dynamic>);
}

/// A class which mocks [JsonConvertible].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonConvertible extends _i1.Mock implements _i10.JsonConvertible {
  MockJsonConvertible() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
