name: pritt_server_core
resolution: workspace

environment:
  sdk: ^3.8.0
dependencies:
  aws_s3_api: ^2.0.0
  aws_signer_api: ^2.0.0
  crypto: ^3.0.6
  file: ^7.0.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path: ^1.9.1
  postgres: ^3.5.6
  pritt_common: ^0.0.1
  retry: ^3.1.2
  slugid: ^1.1.2
dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  mockito: ^5.5.0
  test: ^1.26.3
