name: pritt_common
version: 0.0.1
description: A common package shared by the cli and the server containing the necessary types for both the client and server
resolution: workspace

environment:
  sdk: ^3.6.0
dependencies:
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

  test: any
