
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
          include:
          - arch: x64
            runner: macos-13
          - arch: arm64
            runner: macos-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Build
        run: dart run grinder pkg-standalone-macos-${{ matrix.arch }}

      - name: Generate artifact attestation
        if: github.ref_type == 'tag'
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: build/*.tar.gz
