name: Release of CLI

on:
  push:
    branches: [ "stable" ]
    tags: ['[0-9]+.[0-9]+.*']

### ${{ secrets.GITHUB_TOKEN }} ###4

jobs:
  build_linux:
    permissions:
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build_macos:
    permissions:
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  build_windows:
    permissions:
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
  
  
  release-github:
    runs-on: ubuntu-latest
