# Created with package:mono_repo v6.6.3
name: Dart CI
on:
  pull_request:
    branches:
      - main
      - stable
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: "test; PKG: common; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:common;commands:test_3"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:common
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: "3.6.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: common_pub_upgrade
        name: common; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: common
      - name: common; dart test
        run: dart test
        if: "always() && steps.common_pub_upgrade.conclusion == 'success'"
        working-directory: common
  job_002:
    name: "unit_test; PKG: cli; `dart test test/unit/** --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: "3.6.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: cli_pub_upgrade
        name: cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: cli
      - name: "cli; dart test test/unit/** --test-randomize-ordering-seed=random"
        run: "dart test test/unit/** --test-randomize-ordering-seed=random"
        if: "always() && steps.cli_pub_upgrade.conclusion == 'success'"
        working-directory: cli
    needs:
      - job_001
  job_003:
    name: "unit_test; PKG: server; `dart test test/unit --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:server;commands:test_4"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:server
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: "3.6.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
      - name: "server; dart test test/unit --test-randomize-ordering-seed=random"
        run: "dart test test/unit --test-randomize-ordering-seed=random"
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
    needs:
      - job_001
  job_004:
    name: "integration_test; PKG: cli; `dart test test/cli/**`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: "3.6.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: cli_pub_upgrade
        name: cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: cli
      - name: "cli; dart test test/cli/**"
        run: "dart test test/cli/**"
        if: "always() && steps.cli_pub_upgrade.conclusion == 'success'"
        working-directory: cli
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "integration_test; PKGS: cli, server; `dart test test/integration/**`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli-server;commands:test_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0;packages:cli-server
            os:ubuntu-latest;pub-cache-hosted;sdk:3.6.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: "3.6.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: cli_pub_upgrade
        name: cli; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: cli
      - name: "cli; dart test test/integration/**"
        run: "dart test test/integration/**"
        if: "always() && steps.cli_pub_upgrade.conclusion == 'success'"
        working-directory: cli
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
      - name: "server; dart test test/integration/**"
        run: "dart test test/integration/**"
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
    needs:
      - job_001
      - job_002
      - job_003
