# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Server Testing

on:
  pull_request:
    branches: [ "main", "stable" ]
    paths:
      - '.github/workflows/*_cli.yml'
      - 'cli/**'
      - 'common/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      # Your project will need to have tests in test/ and a dependency on
      - name: Run tests
        run: dart -C cli test


      # TODO: Set up testing for directory
