# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Server Testing

on:
  pull_request:
    branches: [ "main", "stable" ]
    paths:
      - '.github/workflows/*_server.yml'
      - 'server/**'
      - 'common/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install Global dependencies
        run: dart pub get

      - name: Install dependencies
        run: dart pub get
        working-directory: server

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
        working-directory: server

      # TODO: Set up testing for containers