name: pritt_webgen

environment:
  sdk: ^3.6.0
dependencies:
  args: ^2.7.0
  json_annotation: ^4.9.0
  node_interop: any
  node_io: ^2.3.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
